spring:
  application:
    name: customer
  cloud:
    nacos:
      discovery:
        server-addr: 121.37.247.88:8848
      config:
        server-addr: 121.37.247.88:8848
#  config:
#    import: nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
server:
  port: 9001