spring:
  application:
    name: customer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#      config:
#        server-addr: 121.37.247.88:8848
#  config:
#    import: nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
server:
  port: 9003
dubbo:
  registry:
    address: nacos://127.0.0.1:8848