spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.255.10:8848
#      config:
##        file-extension: yaml
#        server-addr: 121.37.247.88:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
#  config:
#    import: nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
server:
  port: 9000
dubbo:
  registry:
    address: nacos://192.168.255.10:8848